spring:
  application:
    name: hwf
  datasource:
    url: jdbc:postgresql://localhost:5432/housewith
    username: kimmj
    password: 598618
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

univcert:
  key: key1234
