spring:
  application:
    name: hwf
  datasource:
    url: jdbc:postgresql://housewith.cn8ua6gwskmx.ap-northeast-2.rds.amazonaws.com:5432/housewith
    username: hwadmin
    password: housewith0711!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

ErrorCode:
  Request:
    UNAVAILABLE_REQUEST_STATUS : "UNAVAILABLE_REQUEST_STATUS"
    UNAVAILABLE_REQUEST_NULL : "NOTHING"
    REQUEST_OVERFLOW : "REQUEST_OVERFLOW"
    VALUE_DUPLICATED : "UNAVAILABLE_CAUSE_DUPLICATED"
  Param:
    INVALID_JOIN_STATUS : "INVALID_JOIN_STATUS"

JWT:
  # 나중에 수정할 비밀키입니다.
  SecretKey: "pT+HzrT8gQkRpGJzxrfEFiS2yZPLClVhRxn3GuRIq2U="

univcert:
  key: key1234

github:
  url: "https://github.com/KimMJ9911/House-With.git"
