name: Simple Build Test

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 실행됨

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub에서 제공하는 우분투 가상환경

    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v4

    - name: JDK 21 설치
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Gradle 실행 권한 부여
      run: chmod +x ./gradlew

    - name: Gradle 빌드 실행
      run: ./gradlew clean build
